### ISSUE TITLE
Can't Resolve Crypto Error Using Angular 6

### ISSUE THREAD

**Issue by cbilliau** [actualreports/pdfgeneratorapi-nodejs#3]
Using Angular 6.1.9

Recently added pdfgeneratorapi to package.json and am receiving the following error on compiling:
`ERROR in ./node_modules/pdf-generator-api/index.js
Module not found: Error: Can't resolve 'crypto' in '.../frontend/node_modules/pdf-generator-api'`

**Comment by crutchcorn** [comment]
This is because `crypto` is a node package built into the node installer itself:


https://nodejs.org/api/crypto.html

This module is meant for use in Node, not general JavaScript environments (like the browser)

That said, to the maintainers of this package - be aware that it would be relatively trivial to provide edgecase support for something like this by allowing a seperate `signature` to be over-writtenly added. This would enable this module to run directly from the client itself

Although THAT said, a seperate thing to be aware of @cbilliau is that you likely don't WANT to run this from your client-side app. You'd be exposing your API _AND_ secret key, which is essentially the keys to your pdfgenerator kingdom
